version: '2'
services:
  db:
    image: postgres
    expose: 
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stock_exchange
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
  server:
    restart: always
    build: .
    user: nobody
    volumes:
      - .:/code
    ports:
      - "12345:12345"
    expose:
      - "12345"
    depends_on:
      - "db"
  